### ISSUE TITLE
Particles going off the top of the screen

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#10]
They should be bouncing back in the module console

**Comment by nunoh** [comment]
This is still happening when gravity is off and changing the speed fader from high to low fast.

**Comment by nunoh** [comment]
Assigning this to you @Oscar-Rodrigues, since you're more aware of the inner workings of the whole gravity thing.

Btw, I was reading the other day about it and it seems that the de facto standard for 2D physics engine is [Box2D](http://box2d.org/) and there is an OF addon for it, [ofxBox2d](https://github.com/vanderlin/ofxBox2d). It would have taken care of a lot of the issues that we had and would allows to do a lot in supposedly a rather easy way. Certainly something that would be nice to know for future projects and maybe even this one in later into the project.

**Comment by Oscar-Rodrigues** [comment]
This is actually not an easy fix. The reason for it is that reasoning behind the gravity mechanics assume that the fader would not be changed during each cycle (each bounce), so a major rework is needed. I'm going to commit a simple hot-fix, just to keep everything less weird, and keep this issue in standby while I investigate some ideas (I've got something in my mind already).

**Comment by nunoh** [comment]
Whats the status of this @Oscar-Rodrigues after yesterday meeting? Are you (we?) still considering changing this or leave as is?

**Comment by nunoh** [comment]
bumping @Oscar-Rodrigues

**Comment by Oscar-Rodrigues** [comment]
Leave it as is for now. If we get to implement the mechanics change on
time, it will be automatically solved, so this is dependent on that, no
need to think of this as a separate issue.

Em ter, 1 de set de 2015 às 16:23, Nuno Hespanhol notifications@github.com
escreveu:

**Comment by nunoh** [comment]
Closing as this is not happening as of right now.
