### ISSUE TITLE
Include small info button at bottom right corner

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#111]
As of now, you need to click the arrow for it to go up, which doesn't make much sense.

**Comment by nunoh** [comment]
This has strong usability issues with Android ecosystem (as well as iOS I really think). Should go for a info button at lower right corner like before. Changing title..

**Comment by Oscar-Rodrigues** [comment]
@nunoh I guess this is finished and tested by now, right? Shall we close it?

**Comment by nunoh** [comment]
This is officially deprecated by now as we are going with swipe up instead. So, closing it.
