### ISSUE TITLE
About image distortion - tablet

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#131]
On iPad, when changing from landscape to portrait and then bringing the about menu up, the about image becomes distorted.
![simulator screen shot 31 mar 2017 17 50 41](https://cloud.githubusercontent.com/assets/4632023/24560405/99d42934-163a-11e7-8f40-d91f92ec0cbc.png)

**Comment by nunoh** [comment]
It's probably not the best fix, that it would solve the problem. @Oscar-Rodrigues What do you think we just allow to "pull" the menu up when in landscape mode?

**Comment by Oscar-Rodrigues** [comment]
Sounds good to me

**Comment by nunoh** [comment]
This is fixed in latest release in App Store, therefore closing.
