### ISSUE TITLE
Loop speed should be the same as gravity

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#15]

**Comment by nunoh** [comment]
@Oscar-Rodrigues We have to define better how loop speed should work. What we talked about so far was to make it the same as the current speed value when in "gravity" mode. Though this might be an option this actually implies that, even though the loop speed fader might be in the same position for different modules, the velocity of the particles might be different, depending on the velocity the particle had in "gravity" mode immediately before loop mode was activated. We are ok with this, or should we rethink that?

**Comment by nunoh** [comment]
As of commit 4c460063dc081 this doesn't apply anymore as well.
