### ISSUE TITLE
Marks at the bottom of the screen

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#20]
so that we know where the limits are

**Comment by nunoh** [comment]
What option do you think it's better? @Digitopia/owners 

![screen shot 2015-04-21 at 18 20 12](https://cloud.githubusercontent.com/assets/1161423/7258492/e7974e82-e854-11e4-92f4-4382860c449d.png)

![screen shot 2015-04-21 at 18 17 43](https://cloud.githubusercontent.com/assets/1161423/7258496/e9d7c244-e854-11e4-9bd1-17724deac814.png)

**Comment by jasgomes** [comment]
Eu acho melhor as linhas de cima abaixo

**Comment by Oscar-Rodrigues** [comment]
Também eu. Fixe fixe era essas linhas ficarem mais intensas quando se está
a juntar uma partícula e quase imperceptíveis de resto (como agora)
José Alberto Gomes notifications@github.com escreveu em ter, 21/04/2015
às 22:00 :

**Comment by p1nh0** [comment]
estou cegueta....qual é a diferença ?

**Comment by nunoh** [comment]
estás a falar a sério @p1nh0? :laughing: Uma tem linhas de cima abaixo e a outra só tem na parte inferior. Se carregares nas imagens dá para ver melhor..

**Comment by jasgomes** [comment]
Vai buscar os óculos :)

---

www.jasg.net

No dia 22/04/2015, às 19:24, Nuno Hespanhol notifications@github.com escreveu:
