### ISSUE TITLE
Speed should work the same way in same module

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#26]
@Oscar-Rodrigues @jasgomes This is something we should consider right?

**Comment by Oscar-Rodrigues** [comment]
@nunoh  we should definitely consider having it behave independently of the device, for instance, in the default speed, a particle would always take x seconds to reach the bottom, either in a low quality Android or in a Mac Pro. But I'm not sure I follow you when you say that it should work the same way in the different modules.

**Comment by nunoh** [comment]
I mean the same you sent by email the other day. With the current implementation the speed of the particle is depending of the moment when the loop speed is activated and not exclusively on the fader value.

**Comment by nunoh** [comment]
Can we close this already or better not yet?

**Comment by Oscar-Rodrigues** [comment]
I think so, but better open a separate issue regarding speed independence from the frameRate, to make sure everything runs smoothly

On 25 May 2015 at 14:03:49 , Nuno Hespanhol (notifications@github.com) wrote:

Can we close this already or better not yet?
