### ISSUE TITLE
Remove button causing app to crash

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#44]
I get the following error message:

GamultOSXDebug(6514,0xb0011000) malloc: **\* error for object 0x111cce4: incorrect checksum for freed object - object was probably modified after being freed.
**\* set a breakpoint in malloc_error_break to debug

This probably has something to do with pointer management.

**Comment by nunoh** [comment]
Really? I never had problem with removing using the button. Just as a wild guess, this could be related with you us using different OF version. You're using master right? Btw, seems 0.9.0 is getting closer to release. 13 issues to go :)

**Comment by Oscar-Rodrigues** [comment]
Neither did I, up until last week. Can you test it?

Yes, I am using master!

On 3 Jul 2015 at 16:10:48 , Nuno Hespanhol (notifications@github.com) wrote:

Really? I never had problem with removing using the button. Just as a wild guess, this could be related with you us using different OF version. You're using master right?

**Comment by nunoh** [comment]
Hm.. We should standardize the OF version we develop on. There are inevitably going to be issues if we develop on top of two at the same time. I was reading a bit about it the other day. Seems to me, the best way we should approach this problem is to git clone the whole OF repo and checkout the branch `stable` which is always pointing to the last stable release. That way, we can develop on the same version and still experiment with `master` branch easily (by checking out master in the OF repo whenever we want). Also, if you're using master you're going to get some deprecation warnings and even some possible errors.

**Comment by Oscar-Rodrigues** [comment]
Yes, that’s a good ideia, but I’m not actually sure this one has to do with different oF versions. I think it has to do with basic C++ operations. Let me just investigate a bit.

On 3 Jul 2015 at 16:14:22 , Nuno Hespanhol (notifications@github.com) wrote:

Hm.. We should standardize the OF version we develop on. There are inevitably going to be issues if we develop on top of two at the same time. I was reading a bit about it the other day. Seems to me, the best way we should approach this problem is to git clone the whole OF repo and checkout the branch stable which is always pointing to the last stable release. That way, we can develop on the same version and still experiment with master branch easily (by checking out master in the OF repo whenever we want). Also, if you're using master you're going to get some deprecation warnings and even some possible errors.

**Comment by Oscar-Rodrigues** [comment]
Ok, I found it! The problem was the vector::end() function. It refers to the beyond-the-last element. For instance, if a vector has 3 elements, it returns and iterator to the fourth, which, obviously, doesn't exist.

See here: http://www.cplusplus.com/reference/vector/vector/end/

But how was it working then???

Anyway, now it works perfectly fine.

**Comment by nunoh** [comment]
A clearer solution is even to use the `pop_back()` method.
