### ISSUE TITLE
Adapt layout for Semibreve according to last meeting

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#56]
@Oscar-Rodrigues Can you please share here the drawings you made in the last meeting when we decided which and how many divisions which module would have in the Semibreve layout? So that we can adapt the app accordingly.

**Comment by Oscar-Rodrigues** [comment]
Em ter, 1 de set de 2015 às 17:52, Nuno Hespanhol <notifications@github.com>
escreveu:

**Comment by Oscar-Rodrigues** [comment]
![screen shot 2015-09-04 at 13 21 18](https://cloud.githubusercontent.com/assets/4632023/9683415/e0924fba-5307-11e5-8f94-aa1ec49ecc94.png)

**Comment by nunoh** [comment]
First Module: 3 notes, gongs ?
Second Module: 7 notes, ?
Third Module: 7 notes, ?
Fourth Module: 6 notes ?

@Oscar-Rodrigues @p1nh0 @jasgomes Can anyone tell me the name of the instruments so that I can know which samples should be triggered? Thanks.

**Comment by Oscar-Rodrigues** [comment]
Not me...  Not even with that high quality drawing!!

**Comment by nunoh** [comment]
1: Kethuk
2: Gender
3: Saron
4: Bonang

**Comment by nunoh** [comment]
Looking like this now (still not final version)

<img width="1280" alt="screen shot 2015-09-15 at 16 35 11" src="https://cloud.githubusercontent.com/assets/1161423/9881472/e8e5fbd0-5bc7-11e5-9718-772dad7b354b.png">
