### ISSUE TITLE
Implement proper design

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#58]
<img width="379" alt="screen shot 2015-09-15 at 17 28 54" src="https://cloud.githubusercontent.com/assets/1161423/9882948/444715d4-5bcf-11e5-9035-24687558d4d5.png">
Info screen:

App Screen with bar showing:

<img width="1211" alt="screen shot 2015-09-15 at 16 53 42" src="https://cloud.githubusercontent.com/assets/1161423/9881999/693cc802-5bca-11e5-873d-7b97eb671862.png">

Interface Module mockup: 
<img width="1215" alt="screen shot 2015-09-15 at 16 53 33" src="https://cloud.githubusercontent.com/assets/1161423/9881995/64cb12e2-5bca-11e5-9bc7-40c8d341eac0.png">

Including PDF for full reference (might be good for exact measurements or colors):
[Gamult d01.pdf | uploaded via ZenHub](https://files.zenhub.io/55f83eef39c9a2fb7bee607e)

**Comment by nunoh** [comment]
##### Design
- [x] scale of greys
- [x] implement inner circle different color
- [x] ask Tiago (designer) for the font type file
- [x] change font to match design and color (awaiting Tiago's input)

##### Transitions
- [x] add Digitopia's splash screen
- [x] restructure code to use a enum state variable rather than booleans, cause it will get cumbersome if not
- [x] transition from `SPLASH_SCREEN` to `ABOUT` with fade out
- [x] image for the arrow to bring from `APP` into `BAR`
- [ ] make the animations be nonlinear (accelerate beginning and slow down at end, which should make them a bit nicer)

##### Module UI
- [x] reorganize layout according to drawing
- [x] implement remove all button
- [x] decide about the old button style: if leave or refactor and how

**Comment by nunoh** [comment]
In last meeting, of 10th September, the following was decided:
- Entering the application (full start and not resume) shows the splash screen logo with Digitopia/Casa da Musica, just like in PORTOphone app.
- Then it goes (automatically or after a click, check PORTOphone here) to the info screen above, where some info text will already be being displayed. Touching somewhere again will make the screen descend until it's just a tiny thing in the middle (like we talked in the meeting).
- Pressing that tiny arrow will show a bar just like in app screen with bar up, where pressing info will return to info screen, app, will either remain the same or descend the bar.

**Comment by nunoh** [comment]
@Oscar-Rodrigues Refactored how we were handling state transitions in the app, so that it's easier and less error prone, as opposed to the boolean variables that is. Here's a diagram just for clarification and quick reference.

![gamult states - new page 1](https://cloud.githubusercontent.com/assets/1161423/9977365/4fe29a14-5efc-11e5-9229-4935f68eac00.png)

**Comment by Oscar-Rodrigues** [comment]
Just FYI, we are deciding to leave the button style as is, without changes.

**Comment by nunoh** [comment]
Regarding the only checklist item not checked of the non-linear animations, decided not do it and go with different speed according from which state they are transitioning to and from. Hence, closing this issue.
