### ISSUE TITLE
Particles close to right border are being cut

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#59]
As in attached screenshot. This is not happening in the left border.

![screen shot 2015-09-18 at 16 41 13](https://cloud.githubusercontent.com/assets/4632023/9963664/46fdcc80-5e24-11e5-9519-8635b794657d.png)

**Comment by nunoh** [comment]
Isn't this because of the newly updated colors for the background of the modules? Like that being drawn after the particles instead of before? If that's the case, we should just call the `drawParticles()` I believe at the end of the `draw()` method rather than the beginning.

**Comment by Oscar-Rodrigues** [comment]
It is, yes, but it's not that simple. It's already being called at the end of the `draw()` method, but the problem comes between different modules. So we call everything on the `draw()` of module 0, including particles, then proceed to module 1. Module 1's background will draw on top of module 0's particles.

I'll have a look :)

**Comment by nunoh** [comment]
Got it :+1:
