### ISSUE TITLE
Don't allow creating a particle when the touch is over the console or bar UI

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#68]
Don't allow to create particle. It should be red instead.
<img width="130" alt="screen shot 2015-10-14 at 18 04 11" src="https://cloud.githubusercontent.com/assets/1161423/10491371/576adbec-729e-11e5-95f1-cd0f58d43c6b.png">

In the same way, when the bar at the bottom is up, don't allow the following. It should be red too.
<img width="395" alt="screen shot 2015-10-14 at 18 04 29" src="https://cloud.githubusercontent.com/assets/1161423/10491376/5bca92ae-729e-11e5-8912-1e460912d405.png">

**Comment by Oscar-Rodrigues** [comment]
Not sure this is actually a good thing (I had already noticed it). 

From my perspective, the important part when creating a particle is its center, so if I have a finger pressed above or under the threshold, I wouldn't want to to risk not having a particle created.

For instance, if I press a point say, 10 pixels, underneath the console, it should always create a particle regardless of its size. In the way you are suggesting I could create a small particle but not a large one, which adds an unnecessary level of complexity (as I see it).

We should discuss this on today's rehearsal.

**Comment by nunoh** [comment]
:+1:

**Comment by nunoh** [comment]
Closing after the discussion in the rehearsal yesterday.
