### ISSUE TITLE
Don't allow interaction with what is behind the bar

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#69]
When the bar is up, one can still click and interact with what is underneath: only "creating red touches", but still, that shouldn't be possible.

<img width="1201" alt="screen shot 2015-10-14 at 18 04 48" src="https://cloud.githubusercontent.com/assets/1161423/10491462/b4005b84-729e-11e5-9679-391ec8bd357f.png">

**Comment by Oscar-Rodrigues** [comment]
This is solved, but just FYI, my approach was: if a user clicks somewhere in the bar, forget that click altogether, so even if you move it up to the "particle creation area", it will not be taken into account.

**Comment by nunoh** [comment]
That's great! That's exactly how we are handling the same kind of clicks in the console window at the top.

**Comment by Oscar-Rodrigues** [comment]
My thoughts exactly!
