### ISSUE TITLE
Fix arrow transparency

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#73]
When app is in a state different than "APP", the arrow is not being drawn correctly.

**Comment by nunoh** [comment]
Got a workaround for this that fixes it. Just draw the arrow rect when in `APP` mode. If in `BAR_ASCENDING`, `BAR_DESCENDING` and `BAR` just draw the arrow without the surrounding rect. Looks ok if you ask me. 

<img width="1280" alt="screen shot 2015-10-27 at 16 00 52" src="https://cloud.githubusercontent.com/assets/1161423/10763968/eb4487bc-7cc3-11e5-98e9-e90784f8092a.png">

**Comment by nunoh** [comment]
Reopening to close with commit message.
