### ISSUE TITLE
Commit xcsharedata/ to repo

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#79]
We were having a too "agressive" `.gitignore` that was ignoring the `xcsharedata` folder of the Xcode project, this was resulting in not sharing project definitions such as schemes and some other project definitions. More info [here](http://stackoverflow.com/a/19321365/161746).

So, please do commit those files to the repo so that I can use them @Oscar-Rodrigues, since you already have them working. I lost them after doing a fresh `git clone` of the repo before.

Simply pulling the changes and committing again should do it:

``` bash
git pull
git status # to review what you will commit
git add . # this should work most probably
git commit -m "Fixes #79 (commit xcshareddata to repo)"
git push # you might need "git push origin master" according to your own local git configs
```

**Comment by Oscar-Rodrigues** [comment]
@nunoh , I have nothing named `xcsharedata` or even `xcuserdata` in my project. So I have nothing to commit...

**Comment by nunoh** [comment]
Don't you have this folder `Gamult_osx.xcodeproj/project.xcworkspace/xcshareddata/`?

**Comment by Oscar-Rodrigues** [comment]
Nop, only a `Gamult_osx.xcodeproj/xcuserdata` but also a `Gamult_osx.xcodeproj/project.xcworkspace/xcuserdata`

**Comment by Oscar-Rodrigues** [comment]
But aren't those packages included in the `Gamult_osx.xcodeproj` file when committing, now that we don't have it on `.gitignore`?

**Comment by nunoh** [comment]
> Nop, only a Gamult_osx.xcodeproj/xcuserdata but also a Gamult_osx.xcodeproj/project.xcworkspace/xcuserdata

Hm.. Ok. That's a bit weird. Let's check that in the meeting most probably then.

> But aren't those packages included in the Gamult_osx.xcodeproj file when committing, now that we don't have it on .gitignore?

`Gamult_osx.xcodeproj` is a folder not a file. That should have been the case, but in your last push, even with the updated `.gitignore` they aren't still in the repo, which makes sense if you don't have them locally.

**Comment by nunoh** [comment]
This was truly a silly mistake of both me and well @Oscar-Rodrigues too, since we both didn't realize we are talking about different projects. I didn't want to mess with project configurations because I though @Oscar-Rodrigues had done that already, when in fact he had done it for PORTOphone not Gamult. So, of course you didn't have the files I was going for :sweat_smile: . Anyway, solved and closing.
