### ISSUE TITLE
Implement portrait mode for mobile

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#86]
As discussed, when smartphone is on Portrait mode, display only one Module.

**Comment by nunoh** [comment]
More info in this issue #60.

**Comment by Oscar-Rodrigues** [comment]
@nunoh, been thinking about this one for a while. I think the best development strategy for now would be to completely separate the iPad and iPhone versions. So we should start working on an iPhone only version that only allows you to work in Portrait mode, adding some rectangles at middle left and middle right to allow you to change instruments. This would later be replaced with the swipe specific code. We should use the `#define TARGET_OF_IPHONE` macro. 

So we would only start merging this code into the iPad app as soon as it is working perfectly on iPhone, as we already have an iPad version that is working well.

What do you think?

**Comment by nunoh** [comment]
I think that is a rather smart solution :+1: and strangely enough we haven't consider it until now. The more difficult part is going to be to maintain state between portrait and landscape mode as we discussed. With this solution you propose, we temporarily avoid that problem while adding a lot of value. I'll be working on it.
