### ISSUE TITLE
Make UI relative to module

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#88]
This is something that we've been postponing recurrently since some time now. And now that we need to have the UI in portrait mode (#86), we probably shouldn't do that anymore.

What do you think @Oscar-Rodrigues?

_Remainder: It's important to make the measures relative to the module and not the screen dimensions._

**Comment by Oscar-Rodrigues** [comment]
Yes, definitely. I'll start working on it.

**Comment by nunoh** [comment]
Nice. :+1: 

(making this issue assigned to you and moving it to the "In Progress" pipeline then)

**Comment by Oscar-Rodrigues** [comment]
There are still a few exceptions, such as font size and some minor padding being done with pixels, but I think it’s best to leave it as is. Tested on multiple devices and screens. Works well.
