### ISSUE TITLE
Rethink initial screens for portrait mode

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#91]
For the iPhone version the initial screens we have so far, won't work for the simple reason that they were thought to be landscape whereas the iPhone version is always in portrait.

**Comment by jasgomes** [comment]
Can't you just flip and cut the what is outside the screen?

**Comment by nunoh** [comment]
I am talking about this picture @jasgomes

![about7](https://cloud.githubusercontent.com/assets/1161423/14289331/35a9c4ae-fb52-11e5-898a-408ff02b0305.png)

So no, that wouldn't really work :smile:

Something as simple as rearranging the info would work though I guess. 

Should we ask Tiago Carneiro for that?

**Comment by jasgomes** [comment]
You're right.

I think we should ask Tiago

**Comment by nunoh** [comment]
Closing this, as already mentioned in the more general #97.
