### ISSUE TITLE
Decide on swiping behaviour

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#93]
So far we mentioned how when swiping the particles would remain hidden, so that when bringing that same module back the particles would still be there (#60).

However there is also this obvious possibility, which we haven't addressed so far, which is of when swiping just change the samples and not a full module, like using the same particles and swiping to choose the "best" sound, which is arguably a good "music composition pattern".

Which one should we go with?

**Comment by jasgomes** [comment]
I'm not sure about it. Both work.
but I think maintaining the particles and just changing the samples is the
best option.

**Comment by nunoh** [comment]
Ok!

**Comment by nunoh** [comment]
While implementing this I thought of the following that might invalidate that option. What if I am in module 1, place some particles, swipe to module 2 to experience the sound. Go to landscape and see module 2 with particles and 1 without. Now if going to portrait again, I am stuck in module 2. While the "paradigm" makes sense, it doesn't work for what we've designed about the app so far. Seems now to me there is actually no other solution than what we thought initially to being with.

**Comment by nunoh** [comment]
Conclusion in last meeting:

> So, just for keeping everything organized, this is how we should switch between portrait and landscape modes on the iPad/Android tablets:
> Open in Landscape mode. All modules functional;
> Register the module we last interacted with as the "active" module in landscape. When no interaction has taken place, if defaults to the first module;
> When switching to Portrait, focus on the "active" module and freeze/pause all others. Only the active module plays;
> When switching back to landscape, all modules are unfreezed/unpaused and they begin playing again.

**Comment by nunoh** [comment]
Can close this issue, as already discussed in meeting and implemented in code accordingly.
