### ISSUE TITLE
Fader size not setting properly when switching between portrait and landscape mode

### ISSUE THREAD

**Issue by Oscar-Rodrigues** [Digitopia/Gamult#94]
I think this is because when in portrait it assumes the max number of modules (those of landscape mode). See image:

![screen shot 2016-04-07 at 16 19 17](https://cloud.githubusercontent.com/assets/4632023/14356444/d115cccc-fcdc-11e5-91c8-a9ae70f594a4.png)

Assigning to @nunoh since he is familiar with the mode switching mechanics.

**Comment by nunoh** [comment]
(this is already fixed, just waiting for the PR to be merged after confirming sth with @Oscar-Rodrigues)
